In [3]:
from datascience import *
import numpy as np

## Arrays

In [11]:
## Retrieving a single value from an array
a = make_array(20.11, 88.05, 11.50)
a.item(-2)

88.05

In [15]:
## what if I want to make an array of consecutive numbers?
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
np.arange(0.5, 2.5, 0.5)

array([0.5, 1. , 1.5, 2. ])

In [24]:
## How do I create an array from 0 to 1000 with an interval of 25?
x = 0
y = 1001
z = 25
sum(np.arange(x, y, z))

20500

## Array arithmetic

In [27]:
receipts = a
original_bills = receipts / 1.15
tips = original_bills * 0.15

original_bills

array([17.48695652, 76.56521739, 10.        ])

In [31]:
## How do I make the array with the values 16, 32, 48, 64?
test_array = np.arange(16, 65, 16)

test_array / 4

test_value = 16
test_value / 4

4.0

In [36]:
#A
np.arange(5) ** 2

array([ 0,  1,  4,  9, 16])

In [39]:
#B 
2 ** np.arange(5)

array([ 1,  2,  4,  8, 16])

In [43]:
#C 
1 / np.arange(5).item(0)

<ipython-input-43-a53a8465bd3b>:2: RuntimeWarning:

divide by zero encountered in true_divide



inf

In [44]:
5 ** -1

0.2

In [41]:
np.arange(5) ** (-1)

ValueError: Integers to negative integer powers are not allowed.

In [108]:
denominators = np.arange(1, 10000, 2)
signs = (-1) ** np.arange(10000/2)
leibniz = 4 * sum((1/denominators) * signs)
leibniz

3.141392653591791

In [111]:
(-1) ** np.arange(10)
-1 ** np.arange(10)

array([ 1, -1,  1, -1,  1, -1,  1, -1,  1, -1])

In [46]:
## The Leibniz formula: pi = 4 * (1 - 1/3 + 1/5 - 1/7 + 1/9...)
negative_denominators = np.arange(3, 10000, 4)
positive_denominators = np.arange(1, 10000, 4)
#signs = 
leibniz = 4 * sum((1/positive_denominators) - (1/negative_denominators))
leibniz

3.1413926535917893

In [49]:
service_chg = receipts * 0.03
service_chg * .03

array([0.018099, 0.079245, 0.01035 ])

In [51]:
total = receipts + service_chg
total

array([20.7133, 90.6915, 11.845 ])

In [59]:
midterm_scores = make_array(88, 92, 66, 47, 100, 94, 85)
final_scores = make_array(99, 100, 94, 95, 96, 100, 99)

In [70]:
#final_scores = final_scores / midterm_scores
#final_scores
x = 0

In [85]:
x = x + 1
x

5

## Iteration

In [76]:
## Do something with every value in an array
cheers = make_array("Oski", "says", "Go", "Bears")
word = print("Oski" + "!")
word = "says" + "!"
word = "Go" + "!"
word = "Bears" + "!"


for word in cheers:
    print(word + "!")

SyntaxError: invalid syntax (<ipython-input-76-a18a91b83d95>, line 3)

In [84]:
## Do something many, many times
die_rolls = make_array(1, 2, 3, 4, 5, 6)

for roll in np.arange(50):
    (np.random.choice(die_rolls))
    
len(np.arange(50))

50

In [ ]:
make_array()
make_array("Heads")
make_array("Heads", "Heads")
make_array("Heads", "Heads", "Tails")

In [98]:
## Probability of getting a heads in 1000 flips?
flip = make_array()
coin = make_array("Heads", "Tails")

for i in np.arange(100):
    flip = np.append(flip, np.random.choice(coin))

flip

array(['Heads', 'Heads', 'Tails', 'Tails', 'Tails', 'Tails', 'Tails',
       'Tails', 'Tails', 'Tails', 'Heads', 'Heads', 'Tails', 'Tails',
       'Tails', 'Heads', 'Tails', 'Heads', 'Tails', 'Tails', 'Heads',
       'Heads', 'Heads', 'Heads', 'Heads', 'Tails', 'Tails', 'Tails',
       'Heads', 'Heads', 'Heads', 'Heads', 'Heads', 'Tails', 'Tails',
       'Tails', 'Heads', 'Heads', 'Heads', 'Tails', 'Heads', 'Heads',
       'Tails', 'Tails', 'Tails', 'Heads', 'Tails', 'Tails', 'Tails',
       'Heads', 'Tails', 'Tails', 'Tails', 'Heads', 'Tails', 'Heads',
       'Heads', 'Heads', 'Tails', 'Tails', 'Tails', 'Tails', 'Heads',
       'Tails', 'Heads', 'Tails', 'Tails', 'Heads', 'Heads', 'Tails',
       'Heads', 'Tails', 'Heads', 'Tails', 'Tails', 'Tails', 'Heads',
       'Tails', 'Heads', 'Heads', 'Tails', 'Heads', 'Tails', 'Heads',
       'Tails', 'Tails', 'Tails', 'Tails', 'Tails', 'Heads', 'Tails',
       'Tails', 'Tails', 'Heads', 'Tails', 'Heads', 'Heads', 'Tails',
       'Tails', 'Hea

In [99]:
## Getting the number of heads
sum(flip == "Heads")

43